# Generated by Django 4.2.7 on 2023-12-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='company_name',
            new_name='name',
        ),
    ]
